### ISSUE TITLE
Advisory Group Draft Description and Goals

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/governance#11]
Based on our previous Governance Group meeting on 11 February 2019 21:00-22:00 UTC, I've drafted a description for the Advisory Group (what we will be calling ourselves moving forward). I've also listed 3 draft goals for us to consider moving forward. Please review the draft material, suggest any changes, and/or vote. **Please respond by February 25th.**

Advisory Group Description:
The Library Carpentry Advisory Group is concerned with advocating for and growing the Library Carpentry community.  The Group meets on a bi-monthly basis to discuss, plan, and pursue strategies for involving new and current members in Library Carpentry. The Advisory Group is not a governance group and does not make decisions for the Library Carpentry community. It does occasionally advise Carpentries staff on ways to foster greater participation in the Library Carpentry community. 

Advisory Group Goals for 2019:
- [ ]  Inform the Library Carpentry community about the Advisory Group and that it is a resource for the community.
- [ ]  Check-in with at least 5-10 Library Carpentry community members, see what they are up to following the workshops they hosted, helped with, and/or instructed. 
- [ ]  Draft letter of interest to explore pool of funding to empower libraries to start local Library Carpentry activities

**Comment by pitviper6** [comment]
@libcce this is great! It lays out very clearly what the group does and as importantly, does NOT do. I've stared at it for a while and can't come up with any changes.

The list of goals is good, and also doable! To start making these happen, do we want to create new issues for each one so that we can collaborate and make the process transparent/get input from the community? That second goal could be a great source of future blog posts.

**Comment by libcce** [comment]
@pitviper6 Thanks 😃 I was worried about listing names of community members in an issue. A while ago I started a Google Spreadsheet that we could use? But yes, the 2nd goal would be a great source for stories.

**Comment by jt14den** [comment]
@libcce I made edits below. Adding a `responsible for` instead of `concerned with` and striking `occasionally`. Mainly, so we have higher expectations for the group. I also added some minor edits. 

The Library Carpentry Advisory Group is ~~concerned with~~ `responsible for` advocating for and growing the Library Carpentry community `and movement`. The Group meets ~~on a~~ bi-monthly ~~basis~~ to discuss, plan, and pursue strategies for involving new and current members in Library Carpentry. The Advisory Group is not a governance group and does not make decisions for the Library Carpentry community. It does ~~occasionally~~ advise Carpentries staff on ways to foster greater participation `and engagement` in the Library Carpentry community.

**Comment by libcce** [comment]
Looks good @jt14den Please, everyone else @chodacki @jezcope @cmacdonell @weaverbel  have a look as well by Feb 25th. Thanks!

**Comment by libcce** [comment]
Missed @chodacki's thumps up so looks like you are set?

**Comment by chodacki** [comment]
Yep, I like it.

**Comment by cmacdonell** [comment]
Hi, sorry for the delay. It looks good to me. I like @jt14den's edits. I might also suggest change "It does advise Carpentries staff" to "It advises...".

**Comment by jezcope** [comment]
Sorry for the delay! Thanks @libcce, looks good to me, though I agree with other comments above about strengthening the language by removing hedging words like "occasionally". The phrase "critical friend" has worked well in the past for groups like this I've been on. I might also swap the order of the final two sentences. So something like:

> The Advisory Group acts as a critical friend to Carpentries staff and advises on ways to foster greater participation in the Library Carpentry community. It is not a governance group and does not make decisions for the Library Carpentry community.

**Comment by libcce** [comment]
Thanks everyone for the feedback!
