### ISSUE TITLE
Blogpost on recent LC publications and Zotero Collection

### ISSUE THREAD

**Issue by arieldeardorff** [LibraryCarpentry/governance#30]
In our July LC Advisory Group Meeting we discussed highlighting some recent LC-related publications and creating a Zotero collection where we can gather and share these publications going forward. 

1. I have started an outline for a [draft blogpost ](https://docs.google.com/document/d/18YScatzmZA8XV7uRDUrFi1Tg47-XOcNSQfvULw_AEXs/edit?usp=sharing). Feel free to edit away and add short descriptions of your articles @davidfkane and @PhilReedData

2. I created a public Zotero group called [LibraryCarpentry](https://www.zotero.org/groups/2540224/librarycarpentry). I think anyone can see the articles but they need to become members in order to upload their own materials. Currently I am the owner but we can also transfer this to a Carpentries account if this makes more sense. Is this the best way to approach this? 

People: @chodacki @davidfkane @PhilReedData

**Comment by PhilReedData** [comment]
Hi @arieldeardorff, many thanks for this excellent work.
1
I have written a description for my part. I've asked Nilani to have a quick look through it too (she is one of our LC instructors who features in my publication). I've snuck in a link to our TEI lesson because the one in my publication is no longer working (we just migrated to the Carpentries Incubator).

I think your introduction is good. Should we have a summary short paragraph at the very end? We could put the Zotero bit at the end, so there is an action on the reader if they want to continue to read more, go to the Zotero group. I hope that doesn't risk people not seeing it though, if they have to scroll, so we could at least mention it briefly at the start.

2
I have no experience of Zotero so I don't feel I can comment on it but I will ask questions. Am I right in thinking that any article we add to the group gets assigned a DOI (if it doesn't already have one), making it easier for people to reference? And anyone using Zotero referencing tools can search for the articles? I shall register and upload my article. Is there an example in SWC or DC to compare?

**Comment by arieldeardorff** [comment]
Thanks for adding your text @PhilReedData! I like the idea of adding a "call to action" at the end to get folks to check out the Zotero links but agree that it might be good to include it at the beginning as well.

I don't believe that Zotero gives out DOIs for articles (you might be thinking of the Zenodo repository?) but I think that anything that we add will be available to folks that look at our collection. I think you need to be a member of a collection to be able to search for things but I am not certain about that. Finally, I don't think there is anything similar for SWC or DC but if we thought this worked well we could certainly recommend it!

Please do try and upload your article to the collection as I am interested to see what the process looks like from your end (and if I need to approve it). Thanks!

**Comment by PhilReedData** [comment]
Ah, I was confusing Zotero and Zenodo, well spotted, thank you.

I have uploaded my article to the collection now, it seems to have worked without requiring approval. I guess anyone could do that, unlikely as it may be, so we may wish to keep an eye on that collection if it does not notify you to edits made by other people. 

I think the article is ready to go now.

**Comment by arieldeardorff** [comment]
Thanks all! I will send this over to the Carpentries communication team for publishing!

**Comment by arieldeardorff** [comment]
Post is now live: https://carpentries.org/blog/2020/09/library-carpentry-publication-showcase/

Nice work everyone!

**Comment by davidfkane** [comment]
Dear All,

I am really sorry that I was unable to attend the meeting today.  I had too many things that required urgent attention tonight.  It was great to see the blog post published.

In related news, I will be heading up a skills working group for our National Open Research Forum.  The purpose of the forum is to drive a cultural change in Irish research towards openness and reproducibility – We will be publishing an action plan or roadmap in about 18 months from now.  This will likely act on 2 main points of leverage: Rewards and Incentives for Open Research and Skills and Training.  One of the avenues that I want to explore how we can use and build on the Carpentries to achieve this in Ireland.  I don’t know too much now, but I will be able to fill you in in more detail nearer the time.

Anyway, stay well and talk to you all soon.

David Kane

--



--
